#!/bin/sh /etc/rc.common
# Example script
# Copyright (C) 2007 OpenWrt.org

USE_PROCD=1
START=95

start_service() {
        procd_open_instance
        procd_set_param respawn
        procd_set_param stderr 1
        procd_set_param stdout 1
        procd_set_param command /etc/clash/clash -d /etc/clash
        procd_close_instance
		iptables -I FORWARD -o utun -j ACCEPT
}
