name: Update Premium Core
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'version of Clash Premium, such as 2022.05.18'
        required: true
        type: string
env:
  download_version: ${{ github.event.inputs.version }}
  download_url: https://release.dreamacro.workers.dev
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main
    - name: Init Dependencies
      run: |
        wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
        wget https://github.com/upx/upx/releases/download/v3.93/upx-3.93-amd64_linux.tar.xz
        tar xf upx-3.96-amd64_linux.tar.xz
        tar xf upx-3.93-amd64_linux.tar.xz
    - name: Download Core
      run: |
        archs="386 amd64 armv5 armv7 arm64 mips-softfloat mipsle-hardfloat mipsle-softfloat"
        mkdir tmp
        for arch in ${archs};do
          wget "${download_url}/${download_version}/clash-linux-${arch}-${download_version}.gz" -O - | gunzip -c > ./tmp/clash-linux-${arch}
          chmod +x ./tmp/clash-linux-${arch}
          if [ "${arch}" != "armv5" ];then
            if [[ ${arch} == mips* ]];then
              ./upx-3.93-amd64_linux/upx ./tmp/clash-linux-${arch}
            else
              ./upx-3.96-amd64_linux/upx ./tmp/clash-linux-${arch}
            fi
          fi
        done
        mv -f ./tmp/clash-linux-arm64 ./tmp/clash-linux-armv8
        rm -fr upx*
    - name: Update
      run: |
        rm -fr ./bin/clashpre/*
        cp ./tmp/* ./bin/clashpre/
        rm -fr ./tmp
        sed -i "s/clashpre_v=.*/clashpre_v=$(./bin/clashpre/clash-linux-amd64 -v 2>/dev/null | sed 's/ linux.*//;s/.* //')/" bin/version
    - name: Commit and push
      run: |
        git config --global user.email "juewuy@gmail.com" && git config --global user.name "Bot"
        git add . && git commit -m "更新Premium内核至${download_version}" || exit 0
        git push
    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 2         
